import { Severity } from './Erro';
export function FuncoesRestritasDesontinuadas(): {
  name: string;
  type: Severity;
  deprecated?: boolean;
  newFunction?: string;
}[] {
  return [
    { name: 'STATICCALL', type: Severity.Error },
    { name: 'PTINTERNAL', type: Severity.Error },
    { name: 'BEGINTRAN', type: Severity.Error },
    { name: 'ENDTRAN', type: Severity.Error },
    { name: 'VALIDAAUTONFE', type: Severity.Warning },
    { name: 'MA410IMPOS', type: Severity.Warning },
    { name: 'MALIBDOFAT', type: Severity.Warning },
    { name: 'TFONTEX', type: Severity.Warning },
    { name: 'NFEPROCNFE', type: Severity.Warning },
    { name: 'AVCPYFILE', type: Severity.Warning },
    { name: 'F_OPCOES', type: Severity.Warning },
    { name: 'AUTONFEENV', type: Severity.Warning },
    { name: 'MASAPREREQ ', type: Severity.Warning },
    { name: 'FTVDVENDA', type: Severity.Warning },
    { name: 'MAALCDOC', type: Severity.Warning },
    { name: 'FISA022TRS', type: Severity.Warning },
    { name: 'FGX_STATF2', type: Severity.Warning },
    { name: 'NG400TAR', type: Severity.Warning },
    { name: 'CODSITRI', type: Severity.Warning },
    { name: 'IW_MULTILINE', type: Severity.Warning },
    { name: 'FWCHKFUNCACCESS', type: Severity.Warning },
    { name: 'WSNFESBRA', type: Severity.Warning },
    { name: 'SPEDDANFE', type: Severity.Warning },
    { name: 'SPEDPEXP', type: Severity.Warning },
    { name: 'STWMANAGREPORTPRINT', type: Severity.Warning },
    { name: 'CBGRVETI', type: Severity.Warning },
    { name: 'A460ESTORNA', type: Severity.Warning },
    { name: 'GETNUMSC7', type: Severity.Warning },
    { name: 'ISCAIXALOJA', type: Severity.Warning },
    { name: 'XNUMCAIXA ', type: Severity.Warning },
    { name: 'CALCEST / CALCESTL', type: Severity.Warning },
    { name: 'FRTGERASL', type: Severity.Warning },
    { name: 'MSCLEARBUFFER', type: Severity.Warning },
    { name: 'CA100INCL ', type: Severity.Warning },
    { name: 'SPEDNFERE2', type: Severity.Warning },
    { name: 'FCARRTAB', type: Severity.Warning },
    { name: 'SALDOTERC', type: Severity.Warning },
    { name: 'FABAIXACR', type: Severity.Warning },
    { name: 'A093PROD', type: Severity.Warning },
    { name: 'OOBJ:GETDATA', type: Severity.Warning },
    { name: 'AVSTACTION', type: Severity.Warning },
    { name: 'VTGETSENHA', type: Severity.Warning },
    { name: 'A450GRAVA', type: Severity.Warning },
    { name: 'OPENSXS', type: Severity.Warning },
    { name: 'FINA110 ', type: Severity.Warning },
    { name: 'A410INCLUI', type: Severity.Warning },
    { name: 'FP_CODFOL', type: Severity.Warning },
    { name: 'NFECABDOC', type: Severity.Warning },
    { name: 'OPENSRC ', type: Severity.Warning },
    { name: 'EXTRACT', type: Severity.Warning },
    { name: 'INCNOTA', type: Severity.Warning },
    { name: 'MOVIMENTO', type: Severity.Warning },
    { name: 'ATFA050', type: Severity.Warning },
    { name: 'PLSQUERY', type: Severity.Warning },
    { name: 'PROXNUM', type: Severity.Warning },
    { name: 'FILE2PRINTER', type: Severity.Warning },
    { name: 'SPF_SEEK ', type: Severity.Warning },
    { name: 'SPF_UPDATE', type: Severity.Warning },
    { name: 'FTVDVENDA', type: Severity.Warning },
    { name: 'APPEND FROM', type: Severity.Warning },
    { name: 'ACPORET ', type: Severity.Warning },
    { name: 'FBUSCACPO', type: Severity.Warning },
    { name: 'A093PROD', type: Severity.Warning },
    { name: 'LASTKEY', type: Severity.Warning },
    { name: 'RPCSETYPE', type: Severity.Warning },
    { name: 'WFPREPENV', type: Severity.Warning },
    { name: 'SALDOB2', type: Severity.Warning },
    { name: 'TMSA050EDI', type: Severity.Warning },
    { name: 'GERATMP', type: Severity.Warning },
    { name: 'A103ATUSE2', type: Severity.Warning },
    { name: 'CTBANFS', type: Severity.Warning },
    { name: 'WAITRUNSRV', type: Severity.Warning },
    { name: 'A103CONSNFESEF', type: Severity.Warning },
    { name: 'SPDCRIATRB', type: Severity.Warning },
    { name: 'A103NFISCAL', type: Severity.Warning },
    { name: 'TTPVIEWER', type: Severity.Warning },
    { name: 'MACANDELF2 ', type: Severity.Warning },
    { name: 'MADELNFS ', type: Severity.Warning },
    { name: 'RET_CBARRA', type: Severity.Warning },
    { name: 'A440LIBERA', type: Severity.Warning },
    { name: 'RFMASHUPS', type: Severity.Warning },
    { name: 'FWJWT2BEAR ', type: Severity.Warning },
    { name: 'CTGERPLAN', type: Severity.Warning },
    { name: 'NXTSX5NOTA', type: Severity.Warning },
    { name: 'FMONTA_TPR', type: Severity.Warning },
    { name: 'COPY TO', type: Severity.Warning },
    { name: 'FDIASAFASPERIODO', type: Severity.Warning },
    { name: 'CBCHKTEMPLATE', type: Severity.Warning },
    { name: 'MSEXCEL', type: Severity.Warning },
    { name: 'ENGSX3117', type: Severity.Warning },
    { name: 'FWLOOKUP', type: Severity.Warning },
    { name: 'FRETAFASBRA', type: Severity.Warning },
    { name: 'FWMVCROTAUTO', type: Severity.Warning },
    { name: 'MONTABLOCK', type: Severity.Warning },
    { name: 'A94EXLIBER', type: Severity.Warning },
    { name: 'ESTRUT', type: Severity.Warning },
    { name: 'A030ALTERA', type: Severity.Warning },
    { name: 'RPCSETTYPE', type: Severity.Warning },
    { name: 'TMSA200PRC', type: Severity.Warning },
    { name: 'HEADPROVA', type: Severity.Warning },
    { name: 'DETPROVA', type: Severity.Warning },
    { name: 'PARAMBOX', type: Severity.Warning },
    { name: 'FWUIWORKSHEET', type: Severity.Warning },
    { name: 'CRDXTITATR', type: Severity.Warning },
    { name: 'MA410RODAP', type: Severity.Warning },
    { name: 'WRITEPROFDEF', type: Severity.Warning },
    { name: 'FINDPROFDEF ', type: Severity.Warning },
    { name: 'CBOPENPORT', type: Severity.Warning },
    { name: 'FATATUEMPN', type: Severity.Warning },
    { name: 'MAAVALSC9', type: Severity.Warning },
    { name: 'VLDLOCALIZ', type: Severity.Warning },
    { name: 'A410MULTT', type: Severity.Warning },
    { name: 'NG420GRAVA', type: Severity.Warning },
    { name: 'A381MANUT', type: Severity.Warning },
    { name: 'MATXFIS', type: Severity.Warning },
    { name: 'MAFISADD  ', type: Severity.Warning },
    { name: 'CTGERCOMP', type: Severity.Warning },
    { name: 'WFNOTIFYADMIN', type: Severity.Warning },
    { name: 'A260PROCESSA ', type: Severity.Warning },
    { name: 'A415TABELA', type: Severity.Warning },
    { name: 'MAAVALCRED ', type: Severity.Warning },
    { name: 'A100DISTRI', type: Severity.Warning },
    { name: '__SAVEPARAM()', type: Severity.Warning },
    { name: 'A110APROV', type: Severity.Warning },
    { name: 'MDEMATA103', type: Severity.Warning },
    { name: 'BUSCATAXA()', type: Severity.Warning },
    { name: 'CRIAVAR', type: Severity.Warning },
    { name: 'E_FIELD', type: Severity.Warning },
    { name: 'APOLECLIENT', type: Severity.Warning },
    { name: 'GETSERVERPORT', type: Severity.Warning },
    { name: 'CHECKSTATION', type: Severity.Warning },
    { name: 'CTBAFIN', type: Severity.Warning },
    { name: 'A415DESCAB', type: Severity.Warning },
    { name: 'A410RECALC', type: Severity.Warning },
    { name: 'X31UPDTABLE ', type: Severity.Warning },
    { name: 'FA050VENC', type: Severity.Warning },
    { name: 'A097PROCLIB', type: Severity.Warning },
    { name: 'MAAVLIBPED', type: Severity.Warning },
    { name: 'A120PEDIDO', type: Severity.Warning },
    { name: 'LOADLAYOUT()', type: Severity.Warning },
    { name: 'FTNFDEVOL', type: Severity.Warning },
    { name: 'FTNFVENDAS', type: Severity.Warning },
    { name: 'TK271CALLCENTER', type: Severity.Warning },
    { name: 'LJ7VENDA', type: Severity.Warning },
    { name: 'MA020PCCGC', type: Severity.Warning },
    { name: 'A140NFISCAL', type: Severity.Warning },
    { name: 'PROCMONITORDOC', type: Severity.Warning },
    { name: 'PROXDOC', type: Severity.Warning },
    { name: 'PUTMARCACOES', type: Severity.Warning },
    { name: 'FA050VISUA', type: Severity.Warning },
    { name: 'SALDOCT7', type: Severity.Warning },
    { name: 'A415BAIXA', type: Severity.Warning },
    { name: 'CBRETETIEAN', type: Severity.Warning },
    { name: 'RETSLDEND', type: Severity.Warning },
    { name: 'A310PROC', type: Severity.Warning },
    { name: 'SPEDNFETRF', type: Severity.Warning },
    { name: 'EECVIEW', type: Severity.Warning },
    { name: 'TK273GRVPTC ', type: Severity.Warning },
    { name: 'APPEXCEL', type: Severity.Warning },
    { name: 'VTNEWEMPR', type: Severity.Warning },
    { name: 'TWFMAIL', type: Severity.Warning },
    { name: 'MACOLSTOFIS', type: Severity.Warning },
    { name: 'WFNOTIFYADMIN ', type: Severity.Warning },
    { name: 'CALLPROC', type: Severity.Warning },
    { name: 'FBUSCASAL ', type: Severity.Warning },
    { name: 'XFUNWIZARD', type: Severity.Warning },
    { name: 'A410ALTERA', type: Severity.Warning },
    { name: 'MC050CON', type: Severity.Warning },
    { name: 'AVGXML2DBF', type: Severity.Warning },
    { name: 'MALIBEROK', type: Severity.Warning },
    { name: 'MARGRDESC ', type: Severity.Warning },
    {
      name: 'FWMSEXCEL',
      type: Severity.Warning,
      deprecated: true,
      newFunction: 'FWMsExcelEx ou FWMsExcelXlsx',
    },
    {
      name: 'FWJsonSerialize',
      type: Severity.Warning,
      deprecated: true,
      newFunction: 'classe JsonObject',
    },
    {
      name: 'FWJsonDeSerialize',
      type: Severity.Warning,
      deprecated: true,
      newFunction: 'classe JsonObject',
    },
  ];
}
